services:
  ##############################################
  #                   MongoDB                  #
  ##############################################
  mongo:
    platform: 'linux/arm64'

  ##############################################
  #           Dapr placement service           #
  ##############################################
  placement:
    platform: 'linux/arm64'

  ##############################################
  #                   ChromaDB                 #
  ##############################################
  chromadb:
    platform: 'linux/arm64'

  ##############################################
  #                 QRY API                   #
  ##############################################
  agntsmth-lab-qry-api:
    platform: 'linux/arm64'

  ##############################################
  #              EMBEDDINGS API                #
  ##############################################
  agntsmth-lab-embeddings-api:
    platform: 'linux/arm64'
